callforit/Models/Conference.cs
using System;

namespace callforit.Models
{
    public class Conference
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string CreatorName { get; set; }
        public DateTime StartDate { get; set; }
    }
}

callforit/Models/EFContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace callforit.Models
{
    public class EFContext : DbContext
    {
        public EFContext() : base("improvingwa-test_db")
        {
        }

        public DbSet<Conference> Conferences { get; set; }
    }
}

callforit/Models/EmailNotification.cs
using System.Runtime.Serialization;

namespace callforit.Models
{
    [DataContract(Namespace = "http://improvingwa.com")]
    public class EmailNotification
    {
        [DataMember]
        public string ToEmailAddress { get; set; }

        [DataMember]
        public string FromEmailAddress { get; set; }

        [DataMember]
        public string Subject { get; set; }

        [DataMember]
        public string Body { get; set; }
    }
}

callforit/Controllers/ConferenceController.cs
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;
using Microsoft.ServiceBus;
using Microsoft.ServiceBus.Messaging;
using Microsoft.WindowsAzure;
using callforit.Models;
using System;

namespace callforit.Controllers
{
    public class ConferenceController : Controller
    {
        //
        // GET: /Conference/

        public ActionResult Index()
        {
            System.Diagnostics.Trace.TraceError("ZOMG this is bad!");
            return View(GetAll());
        }

        //
        // GET: /Conference/Details/5

        public ActionResult Details(int id)
        {
            var existingConference = FindById(id);
            if (existingConference == null) return HttpNotFound();
            return View(existingConference);
        }

        //
        // GET: /Conference/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Conference/Create

        [HttpPost]
        public ActionResult Create(Conference conference)
        {
            if (ModelState.IsValid)
            {
                ClaimsPrincipal principal = ClaimsPrincipal.Current;
                var fullname = string.Format("{0} {1}", principal.FindFirst(ClaimTypes.GivenName).Value,
                                             principal.FindFirst(ClaimTypes.Surname).Value);
                conference.CreatorName = fullname;
                AddOrReplaceConference(conference);
                return RedirectToAction("Index");
            }

            return View(conference);
        }

        //
        // GET: /Conference/Edit/5

        public ActionResult Edit(int id)
        {
            var existingConference = FindById(id);
            if (existingConference == null) return HttpNotFound();
            return View(existingConference);
        }

        //
        // POST: /Conference/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, Conference conference)
        {
            var existingConference = FindById(id);
            if (existingConference == null) return HttpNotFound();

            if (ModelState.IsValid)
            {
                AddOrReplaceConference(conference);
                return RedirectToAction("Index");
            }

            return View(conference);
        }

        //
        // GET: /Conference/Delete/5

        public ActionResult Delete(int id)
        {
            var existingConference = FindById(id);
            if (existingConference == null) return HttpNotFound();
            return View(existingConference);
        }

        //
        // POST: /Conference/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            DeleteConference(id);
            return RedirectToAction("Index");
        }

        #region Private Data Access

        private Conference FindById(int id)
        {
            using (var context = new EFContext())
            {
                return context.Conferences.SingleOrDefault(x => x.Id.Equals(id));
            }
        }

        private void SendEmailNotificationAboutNewConference(Conference conference)
        {
            var namespaceManager =
                NamespaceManager.CreateFromConnectionString(CloudConfigurationManager.GetSetting("CallForItServiceBus"));

            if (namespaceManager.QueueExists("NewConferenceQueue") == false)
                namespaceManager.CreateQueue("NewConferenceQueue");

            var queueClient =
                QueueClient.CreateFromConnectionString(CloudConfigurationManager.GetSetting("CallForItServiceBus"),
                                                       "NewConferenceQueue");

            var notification = new EmailNotification();

            notification.ToEmailAddress = "improvingwa@gmail.com";
            notification.FromEmailAddress = "conferences@callforit.com";
            notification.Subject = "New Conference!";
            notification.Body = String.Format("Great news! {0} has been scheduled for {1}.", conference.Name,
                                              conference.StartDate);

            queueClient.Send(new BrokeredMessage(notification));
        }

        private void AddOrReplaceConference(Conference conference)
        {
            using (var context = new EFContext())
            {
                if (conference.Id == default(int))
                {
                    // Add Scenario
                    context.Conferences.Add(conference);
                    context.SaveChanges();

                    SendEmailNotificationAboutNewConference(conference);
                }
                else
                {
                    // Update Scenario
                    conference = context.Conferences.Attach(conference);
                    context.Entry(conference).State = System.Data.EntityState.Modified;
                    context.SaveChanges();
                }
            }
        }

        private IEnumerable<Conference> GetAll()
        {
            using (var context = new EFContext())
            {
                return context.Conferences.ToList();
            }
        }
        private void DeleteConference(int id)
        {
            using (var context = new EFContext())
            {
                var conf = context.Conferences.SingleOrDefault(e => e.Id == id);
                context.Conferences.Remove(conf);
                context.SaveChanges();
            }
        }
        #endregion
    }
}

callforit/Controllers/HomeController.cs
using System.Web.Mvc;

namespace callforit.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

callforit/Views/Conference/Create.cshtml
@model callforit.Models.Conference

@{
    ViewBag.Title = "Create Conference";
}

<h2>Create Conference</h2>
@using (Html.BeginForm())
{
    <fieldset>
        <legend>Conference</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Url)
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

callforit/Views/Conference/Delete.cshtml
@model callforit.Models.Conference

@{
    ViewBag.Title = "Delete Conference";
}

<h2>Delete Conference</h2>
<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Conference</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Url)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Url)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

callforit/Views/Conference/Details.cshtml
@model callforit.Models.Conference

@{
    ViewBag.Title = "View Conference";
}

<h2>View Conference</h2>
<fieldset>
    <legend>Conference</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Url)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Url)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
<

callforit/Views/Conference/Edit.cshtml
@model callforit.Models.Conference

@{
    ViewBag.Title = "Edit Conference";
}

<h2>Edit Conference</h2>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Conference</legend>

        @Html.HiddenFor(model => model.Id)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Url)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Url)
            @Html.ValidationMessageFor(model => model.Url)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.StartDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.StartDate)
            @Html.ValidationMessageFor(model => model.StartDate)
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

callforit/Views/Conference/Index.cshtml
@model IEnumerable<callforit.Models.Conference>

@{
    ViewBag.Title = "Conferences";
}

<h2>Conferences</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatorName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var conference in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => conference.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => conference.Url)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => conference.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => conference.CreatorName)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = conference.Id })
                    @Html.ActionLink("Details", "Details", new { id = conference.Id })
                    @Html.ActionLink("Delete", "Delete", new { id = conference.Id })
                </td>
            </tr>
        }
    </tbody>
</table>

callforit/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

callforit/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

callforit/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Howdy!</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

callforit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @if (!string.IsNullOrEmpty(User.Identity.Name))
                        {
                            <span>Hello, <span class="username">@User.Identity.Name</span>!</span>
                        }
                        else
                        {
                            <span>&nbsp;</span>
                        }
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Conferences", "Index", "Conference")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>